/**
 * QCOREServerLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Alerts
 */
class Alerts extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cpu = this.constructor.getValue(obj.cpu);
        this.networkIn = this.constructor.getValue(obj.networkIn || obj.network_in);
        this.networkOut = this.constructor.getValue(obj.networkOut || obj.network_out);
        this.transferQuota = this.constructor.getValue(obj.transferQuota || obj.transfer_quota);
        this.io = this.constructor.getValue(obj.io);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cpu', realName: 'cpu' },
            { name: 'networkIn', realName: 'network_in' },
            { name: 'networkOut', realName: 'network_out' },
            { name: 'transferQuota', realName: 'transfer_quota' },
            { name: 'io', realName: 'io' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Alerts;
