/**
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Specs
 */
class Specs extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.disk = this.constructor.getValue(obj.disk);
        this.memory = this.constructor.getValue(obj.memory);
        this.vcpus = this.constructor.getValue(obj.vcpus);
        this.gpus = this.constructor.getValue(obj.gpus);
        this.transfer = this.constructor.getValue(obj.transfer);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'disk', realName: 'disk' },
            { name: 'memory', realName: 'memory' },
            { name: 'vcpus', realName: 'vcpus' },
            { name: 'gpus', realName: 'gpus' },
            { name: 'transfer', realName: 'transfer' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Specs;
