/**
 * QCOREServerLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ListesDeServeur = require('../lib/Models/ListesDeServeur');
const Specs = require('../lib/Models/Specs');
const Alerts = require('../lib/Models/Alerts');
const Backups = require('../lib/Models/Backups');
const Schedule = require('../lib/Models/Schedule');
const SiLeServeurEstDJAllum = require('../lib/Models/SiLeServeurEstDJAllum');
const MError = require('../lib/Models/MError');
const LinodeServersShow = require('../lib/Models/LinodeServersShow');
const Result = require('../lib/Models/Result');
const BaseStatusApi = require('../lib/Models/BaseStatusApi');

const classMap = {
    ListesDeServeur,
    Specs,
    Alerts,
    Backups,
    Schedule,
    SiLeServeurEstDJAllum,
    MError,
    LinodeServersShow,
    Result,
    BaseStatusApi,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
