<?php
/*
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace QCOREApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Alerts implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $cpu public property
     */
    public $cpu;

    /**
     * @todo Write general description for this property
     * @required
     * @maps network_in
     * @var integer $networkIn public property
     */
    public $networkIn;

    /**
     * @todo Write general description for this property
     * @required
     * @maps network_out
     * @var integer $networkOut public property
     */
    public $networkOut;

    /**
     * @todo Write general description for this property
     * @required
     * @maps transfer_quota
     * @var integer $transferQuota public property
     */
    public $transferQuota;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $io public property
     */
    public $io;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $cpu           Initialization value for $this->cpu
     * @param integer $networkIn     Initialization value for $this->networkIn
     * @param integer $networkOut    Initialization value for $this->networkOut
     * @param integer $transferQuota Initialization value for $this->transferQuota
     * @param integer $io            Initialization value for $this->io
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->cpu           = func_get_arg(0);
            $this->networkIn     = func_get_arg(1);
            $this->networkOut    = func_get_arg(2);
            $this->transferQuota = func_get_arg(3);
            $this->io            = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['cpu']            = $this->cpu;
        $json['network_in']     = $this->networkIn;
        $json['network_out']    = $this->networkOut;
        $json['transfer_quota'] = $this->transferQuota;
        $json['io']             = $this->io;

        return $json;
    }
}
