<?php
/*
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace QCOREApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Backups implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $enabled public property
     */
    public $enabled;

    /**
     * @todo Write general description for this property
     * @required
     * @var \QCOREApiLib\Models\Schedule $schedule public property
     */
    public $schedule;

    /**
     * @todo Write general description for this property
     * @maps last_successful
     * @var string|null $lastSuccessful public property
     */
    public $lastSuccessful;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool     $enabled        Initialization value for $this->enabled
     * @param Schedule $schedule       Initialization value for $this->schedule
     * @param string   $lastSuccessful Initialization value for $this->lastSuccessful
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->enabled        = func_get_arg(0);
            $this->schedule       = func_get_arg(1);
            $this->lastSuccessful = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['enabled']         = $this->enabled;
        $json['schedule']        = $this->schedule;
        $json['last_successful'] = $this->lastSuccessful;

        return $json;
    }
}
