<?php
/*
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace QCOREApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Error implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $reason public property
     */
    public $reason;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $reason Initialization value for $this->reason
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->reason = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['reason'] = $this->reason;

        return $json;
    }
}
