<?php
/*
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace QCOREApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LinodeServersShow implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @required
     * @var \QCOREApiLib\Models\Result $result public property
     */
    public $result;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $status Initialization value for $this->status
     * @param Result  $result Initialization value for $this->result
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->status = func_get_arg(0);
            $this->result = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['status'] = $this->status;
        $json['result'] = $this->result;

        return $json;
    }
}
