<?php
/*
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace QCOREApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Schedule implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $day public property
     */
    public $day;

    /**
     * @todo Write general description for this property
     * @var string|null $window public property
     */
    public $window;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $day    Initialization value for $this->day
     * @param string $window Initialization value for $this->window
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->day    = func_get_arg(0);
            $this->window = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['day']    = $this->day;
        $json['window'] = $this->window;

        return $json;
    }
}
