<?php
/*
 * QCOREApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace QCOREApiLib;

use QCOREApiLib\Controllers;

/**
 * QCOREApiLib client class
 */
class QCOREApiClient
{
    /**
     * Singleton access to Servers controller
     * @return Controllers\ServersController The *Singleton* instance
     */
    public function getServers()
    {
        return Controllers\ServersController::getInstance();
    }
    /**
     * Singleton access to QCoreMinecraft controller
     * @return Controllers\QCoreMinecraftController The *Singleton* instance
     */
    public function getQCoreMinecraft()
    {
        return Controllers\QCoreMinecraftController::getInstance();
    }
}
